### ISSUE TITLE
Document homeserver requirements and prerequisites to use Chatterbox

### ISSUE THREAD

**Issue by williamkray** [vector-im/chatterbox#76]
**Is your feature request related to a problem? Please describe.**
The documentation in this repo is pretty sparse, and in my attempts to play with it in my own deployment I've identified that my homeserver needs to allow registration, and that I will also need to presumably generate a registration token to be used to create new users (a feature that is pretty rare to encounter for most homeserver operators, since registration tokens are not supported by arguably the most popular Matrix clients element-[web|android|ios]). Unfortunately, I'm finding these things out simply by rather a lot of trial and error and watching the announcement video trying to glean any information I can, rather than from the setup instructions.

**Describe the solution you'd like**
I would like detailed information about prerequisites to use Chatterbox included in the setup instructions.

**Describe alternatives you've considered**
Use an alternate project - but then I'm not using chatterbox :)

**Comment by Half-Shot** [comment]
This is something I can pick up.
