### ISSUE TITLE
Kind is undefined

### ISSUE THREAD

**Issue by andrejohansson** [vector-im/chatterbox#80]
**Describe the bug**

When a new user tries to chat with me from my page, it seems that the registration on my homeserver is too slow and the user is greeted with an error. Reloading the page or pressing the chat button again corrects the problem. It seems like some race condition from the chat app while waiting for the user registration to complete.

**To Reproduce**

- The **first time** a user visits my page and click the chat icon, the chat box will produce the following error:

    > Something went wrong…can't access property "kind", i is undefined

- In the console, I can see repeatated calls to the register endpoint of my server
- Reloading the page OR pressing the chat button again will make chat work properly

**Expected behavior**
The chat window to load properly on first key press without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/2828428/179068418-58582b73-ea11-4e5c-bcb8-4b87c5061bf7.png)

![image](https://user-images.githubusercontent.com/2828428/179067455-ddc0139f-c234-43fc-a7a7-401a973a43f9.png)

![image](https://user-images.githubusercontent.com/2828428/179068524-b1e92b70-75ea-4bfc-ba1d-c80d23e5b3d6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox Developer
 - Version 103.0b7 (64-bit

**Additional context**
Same behavior in different browsers and on different devices.

**Comment by ptman** [comment]
I have the same problem

**Comment by ptman** [comment]
Upon refresh it does load, but even though it shows invite_user joining, it still states "Waiting for operator to join"

**Comment by MidhunSureshR** [comment]
This should be fixed on main, feel free to reopen if you still have issues.

**Comment by MidhunSureshR** [comment]
> Upon refresh it does load, but even though it shows invite_user joining, it still states "Waiting for operator to join"

That "Waiting for operator to join" is a feature. Change `disable_composer_until_operator_join` to false in config.json to disable this.

**Comment by ptman** [comment]
I get that it's a feature. But the invited user joined. And still the condition to hide that message wasn't met. What is the condition that needs to be satisfied?

**Comment by MidhunSureshR** [comment]
So if you have that feature turned on, your PL is set to a low enough value that you cannot send messages. The invited user must bump your PL up so that you can send messages. I see now that this isn't communicated clearly in the documentation.
